version: '3'
services:

  db:
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./.mysql:/var/lib/mysql

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4567-4599:4567-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      SERVICES: "apigateway,lambda"
      TEST_AWS_ACCOUNT_ID: "123456789012"
      DEBUG: "true"
      LAMBDA_EXECUTOR: "docker"
      LAMBDA_REMOTE_DOCKER: "false"
      DOCKER_HOST: "unix:///var/run/docker.sock"
      LAMBDA_DOCKER_NETWORK: "typescript-refs_default"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:$PWD"